server:
  port: 8189
  servlet:
    context-path: /
spring:
  jpa:
    hibernate:
#      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_default: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=springcrud
    username: postgres
    password: password
springdoc:
  api-docs:
    path : api-docs